version: '3'
services:
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: senha123
      MYSQL_USER: product_user
      MYSQL_PASSWORD: product_user_password
      MYSQL_DATABASE: product

  cadastros-backend:
      build:
        context: ./cadastros/backend
        dockerfile: Dockerfile
      ports:
        - "8080:8080"
      depends_on:
        - mysql
      environment:
        SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/product
        SPRING_DATASOURCE_USERNAME: product_user
        SPRING_DATASOURCE_PASSWORD: product_user_password

  cadastros-frontend:
      build:
        context: ./cadastros/frontend
        dockerfile: Dockerfile
      ports:
        - "3000:80"
