version: '3'
services:
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: senha123
      MYSQL_USER: usuario_ecommerce
      MYSQL_PASSWORD: senha_ecommerce
      MYSQL_DATABASE: ecommerce

  cadastros-backend:
      build:
        context: ./cadastros/backend
        dockerfile: Dockerfile
      ports:
        - "8080:8080"
      depends_on:
        - mysql
      environment:
        SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/ecommerce
        SPRING_DATASOURCE_USERNAME: usuario_ecommerce
        SPRING_DATASOURCE_PASSWORD: senha_ecommerce

  cadastros-frontend:
      build:
        context: ./cadastros/frontend
        dockerfile: Dockerfile
      ports:
        - "3000:80"

  produtos-backend:
      build:
        context: ./produtos/backend
        dockerfile: Dockerfile
      ports:
        - "8081:8081"
      depends_on:
        - mysql
      environment:
        SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/ecommerce
        SPRING_DATASOURCE_USERNAME: usuario_ecommerce
        SPRING_DATASOURCE_PASSWORD: senha_ecommerce    
  produtos-frontend:
      build:
        context: ./produtos/frontend
        dockerfile: Dockerfile
      ports:
        - "3010:81"
